"""Suppression de map_url du modèle Site

Revision ID: 29e4bedaf7e9
Revises: aa030490268a
Create Date: 2025-03-18 10:27:41.230378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e4bedaf7e9'
down_revision = 'aa030490268a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text("SWITCHOFFSET(SYSDATETIMEOFFSET(), '+01:00')"), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text("SWITCHOFFSET(SYSDATETIMEOFFSET(), '+01:00')"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
