"""Ajout des relations one-to-one entre Carte et Etage/Site

Revision ID: 6ab6ef44de68
Revises: 72987f3cbcfb
Create Date: 2025-03-17 16:47:53.756229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab6ef44de68'
down_revision = '72987f3cbcfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etage_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['id'])
        batch_op.create_foreign_key(None, 'etages', ['etage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('site_id')
        batch_op.drop_column('etage_id')

    # ### end Alembic commands ###
